# Use postgres/example user/password credentials
version: '3.1'

networks:
  local-network:
    driver: bridge

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: deondre
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mumbleDB
    ports:
      - 5432:5432
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - local-network
    ports:
      - '6379'